trigger:
  - main

resources:
  repositories:
    - repository: Terraform
      type: github
      name: IsuruGunarathne/Terraform
      endpoint: github.com_IsuruGunarathne

pool:
  vmImage: ubuntu-latest

steps:
  # Checkout the current repository (default behavior)
  - checkout: self

  # Checkout the deployment repository
  - checkout: Terraform

  # Print the configuration template from the deployment repository
  - script: |
      cat Terraform/Azure/config/confTemplate.tfvars
      mkdir Workspace
      cp Terraform/Azure/config/confTemplate.tfvars Workspace/confTemplate.tfvars
      echo ""
      echo "Configuration template copied to Workspace directory"
      cd Workspace
      ls
    displayName: "Fetching configuration template"

  - script: |
      cp PIC-config-mapper/gerate-conf.sh Workspace/generate-conf.sh
      cp PIC-config-mapper/defaultValues.json Workspace/defaultValues.json
      cp PIC-config-mapper/keyMappings.json Workspace/keyMappings.json
      cd Workspace
      chmod +x generate-conf.sh
      ./generate-conf.sh $(env)
    displayName: "Run generator script"

  - script: |
      cd Workspace
      cat conf.auto.tfvars
    displayName: "Print the generated configuration"
