trigger:
  - main

resources:
  repositories:
    - repository: Terraform
      type: github
      name: IsuruGunarathne/Terraform
      endpoint: github.com_IsuruGunarathne

pool:
  vmImage: ubuntu-latest

steps:
  # Checkout the current repository (default behavior)
  - checkout: self

  # Checkout the deployment repository
  - checkout: Terraform

  # Print the configuration template from the deployment repository
  - script: |
      cat Terraform/Azure/config/confTemplate.tfvars
    displayName: "Print configuration template"

  # Run a multi-line script
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: "Run a multi-line script"
