trigger:
  - main

resources:
  repositories:
    - repository: Terraform
      type: github
      name: IsuruGunarathne/Terraform
      endpoint: github.com_IsuruGunarathne

pool:
  vmImage: ubuntu-latest

steps:
  # Checkout the current repository (default behavior)
  - checkout: self

  # Checkout the deployment repository
  - checkout: Terraform

  # Print the configuration template from the deployment repository
  - script: |
      cat Terraform/Azure/config/confTemplate.tfvars
      mkdir Workspace
      cp Terraform/Azure/config/confTemplate.tfvars Workspace/confTemplate.tfvars
      echo ""
      echo "Configuration template copied to Workspace directory"
      cd Workspace
      ls
    displayName: "Print configuration template and copy to workspace"

  - script: |
      cp PIC-config-mapper/generate-conf.sh Workspace/generate-conf.sh
      chmod +x Workspace/generate-conf.sh
      cd Workspace
      ls
    displayName: "Copy configuration generator script to workspace"
